# Generated by Django 3.0.5 on 2020-05-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=60)),
                ('sexo', models.CharField(choices=[('1', 'Masculino'), ('2', 'Feminino'), ('3', 'Outro')], max_length=10)),
                ('senha', models.CharField(max_length=50)),
                ('foto', models.CharField(max_length=100)),
            ],
        ),
    ]
